-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS db_bgefv4_schemav2.bidcontent
(
    id serial NOT NULL,
    bidheader_id integer,
    bidcontent character varying(500) COLLATE pg_catalog."default" NOT NULL,
    gear1_id integer,
    gear2_id integer,
    gear3_id integer,
    gear4_id integer,
    gear5_id integer,
    gear6_id integer,
    gear7_id integer,
    gear8_id integer,
    gear9_id integer,
    gear10_id integer,
    coneditedtime timestamp without time zone NOT NULL,
    bundleimage_id integer,
    bundlesound_id integer,
    CONSTRAINT bidcontent_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS db_bgefv4_schemav2.bidexchange
(
    id serial NOT NULL,
    salesbidder_id integer NOT NULL,
    salesbidheader_id integer NOT NULL,
    purchasebidder_id integer NOT NULL,
    purchasebidheader_id integer NOT NULL,
    agreeddeal boolean DEFAULT false,
    dealtimestamp timestamp without time zone NOT NULL,
    CONSTRAINT bidexchange_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS db_bgefv4_schemav2.bidgenre
(
    id serial NOT NULL,
    bidgenreheader character varying(100) COLLATE pg_catalog."default" NOT NULL,
    user_id integer,
    lastbidheader_id integer,
    numberofbids integer NOT NULL,
    CONSTRAINT bidgenre_pkey PRIMARY KEY (id),
    CONSTRAINT bidgenre_bidgenreheader_key UNIQUE (bidgenreheader)
);

CREATE TABLE IF NOT EXISTS db_bgefv4_schemav2.bidheader
(
    id serial NOT NULL,
    user_id integer,
    bidgenre_id integer,
    bidtypecode integer,
    bidstatus integer,
    bidcontent_id integer,
    bidheadertext character varying(100) COLLATE pg_catalog."default" NOT NULL,
    bidexchange1_id integer,
    bidexchange2_id integer,
    bidexchange3_id integer,
    bidexchange4_id integer,
    bidexchange5_id integer,
    bidstartedtime timestamp without time zone NOT NULL,
    bidendingtime timestamp without time zone NOT NULL,
    hdreditedtime timestamp without time zone NOT NULL,
    CONSTRAINT bidheader_pkey PRIMARY KEY (id),
    CONSTRAINT bidheader_bidheadertext_key UNIQUE (bidheadertext)
);

CREATE TABLE IF NOT EXISTS db_bgefv4_schemav2.client
(
    id serial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(25) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    email character varying(80) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    secondaryemail character varying(80) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    usericon_url character varying(80) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    role_id integer NOT NULL,
    blocked boolean DEFAULT false,
    latestbidheader_id integer,
    CONSTRAINT client_pkey PRIMARY KEY (id),
    CONSTRAINT client_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS db_bgefv4_schemav2.gear
(
    id serial NOT NULL,
    gearbrand character varying(30) COLLATE pg_catalog."default" NOT NULL,
    gearcode integer,
    gearstatus integer,
    bidheader_id integer,
    gearname character varying(100) COLLATE pg_catalog."default" NOT NULL,
    geardetails text COLLATE pg_catalog."default",
    gearstory text COLLATE pg_catalog."default",
    amountoffered integer NOT NULL,
    approxvalue double precision DEFAULT 0.00,
    user_id integer,
    comments text COLLATE pg_catalog."default",
    editedtime timestamp without time zone NOT NULL,
    gearimage_id integer,
    soundclip_id integer,
    CONSTRAINT gear_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS db_bgefv4_schemav2.imagemetadata
(
    id serial NOT NULL,
    imagename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    axsize character varying(10) COLLATE pg_catalog."default" NOT NULL,
    resolution character varying(20) COLLATE pg_catalog."default" NOT NULL,
    image_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT imagemetadata_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS db_bgefv4_schemav2.role
(
    id serial NOT NULL,
    rolename character varying(80) COLLATE pg_catalog."default" NOT NULL,
    registereduser boolean DEFAULT false,
    sellerrole boolean DEFAULT false,
    buyerrole boolean DEFAULT false,
    adminrole boolean DEFAULT false,
    CONSTRAINT role_pkey PRIMARY KEY (id),
    CONSTRAINT role_rolename_key UNIQUE (rolename)
);

CREATE TABLE IF NOT EXISTS db_bgefv4_schemav2.soundclipmetadata
(
    id serial NOT NULL,
    clipname character varying(100) COLLATE pg_catalog."default" NOT NULL,
    format character varying(10) COLLATE pg_catalog."default" NOT NULL,
    quality character varying(30) COLLATE pg_catalog."default" NOT NULL,
    cliplengthinseconds double precision NOT NULL,
    isstereo boolean NOT NULL,
    sample_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT soundclipmetadata_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidcontent
    ADD CONSTRAINT fk_gear1 FOREIGN KEY (gear1_id)
    REFERENCES db_bgefv4_schemav2.gear (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidcontent
    ADD CONSTRAINT fk_gear10 FOREIGN KEY (gear10_id)
    REFERENCES db_bgefv4_schemav2.gear (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidcontent
    ADD CONSTRAINT fk_gear2 FOREIGN KEY (gear2_id)
    REFERENCES db_bgefv4_schemav2.gear (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidcontent
    ADD CONSTRAINT fk_gear3 FOREIGN KEY (gear3_id)
    REFERENCES db_bgefv4_schemav2.gear (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidcontent
    ADD CONSTRAINT fk_gear4 FOREIGN KEY (gear4_id)
    REFERENCES db_bgefv4_schemav2.gear (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidcontent
    ADD CONSTRAINT fk_gear5 FOREIGN KEY (gear5_id)
    REFERENCES db_bgefv4_schemav2.gear (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidcontent
    ADD CONSTRAINT fk_gear6 FOREIGN KEY (gear6_id)
    REFERENCES db_bgefv4_schemav2.gear (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidcontent
    ADD CONSTRAINT fk_gear7 FOREIGN KEY (gear7_id)
    REFERENCES db_bgefv4_schemav2.gear (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidcontent
    ADD CONSTRAINT fk_gear8 FOREIGN KEY (gear8_id)
    REFERENCES db_bgefv4_schemav2.gear (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidcontent
    ADD CONSTRAINT fk_gear9 FOREIGN KEY (gear9_id)
    REFERENCES db_bgefv4_schemav2.gear (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidexchange
    ADD CONSTRAINT fk_bidheader_p FOREIGN KEY (purchasebidheader_id)
    REFERENCES db_bgefv4_schemav2.bidheader (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidexchange
    ADD CONSTRAINT fk_bidheader_s FOREIGN KEY (salesbidheader_id)
    REFERENCES db_bgefv4_schemav2.bidheader (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidexchange
    ADD CONSTRAINT fk_client_p FOREIGN KEY (purchasebidder_id)
    REFERENCES db_bgefv4_schemav2.client (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidexchange
    ADD CONSTRAINT fk_client_s FOREIGN KEY (salesbidder_id)
    REFERENCES db_bgefv4_schemav2.client (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidgenre
    ADD CONSTRAINT fk_bidheader FOREIGN KEY (lastbidheader_id)
    REFERENCES db_bgefv4_schemav2.bidheader (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidgenre
    ADD CONSTRAINT fk_client FOREIGN KEY (user_id)
    REFERENCES db_bgefv4_schemav2.client (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidheader
    ADD CONSTRAINT fk_bidcontent FOREIGN KEY (bidcontent_id)
    REFERENCES db_bgefv4_schemav2.bidcontent (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidheader
    ADD CONSTRAINT fk_bidexchange1 FOREIGN KEY (bidexchange1_id)
    REFERENCES db_bgefv4_schemav2.bidexchange (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidheader
    ADD CONSTRAINT fk_bidexchange2 FOREIGN KEY (bidexchange2_id)
    REFERENCES db_bgefv4_schemav2.bidexchange (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidheader
    ADD CONSTRAINT fk_bidexchange3 FOREIGN KEY (bidexchange3_id)
    REFERENCES db_bgefv4_schemav2.bidexchange (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidheader
    ADD CONSTRAINT fk_bidexchange4 FOREIGN KEY (bidexchange4_id)
    REFERENCES db_bgefv4_schemav2.bidexchange (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidheader
    ADD CONSTRAINT fk_bidexchange5 FOREIGN KEY (bidexchange5_id)
    REFERENCES db_bgefv4_schemav2.bidexchange (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidheader
    ADD CONSTRAINT fk_bidgenre FOREIGN KEY (bidgenre_id)
    REFERENCES db_bgefv4_schemav2.bidgenre (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidheader
    ADD CONSTRAINT fk_bidheader FOREIGN KEY (user_id)
    REFERENCES db_bgefv4_schemav2.bidheader (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidheader
    ADD CONSTRAINT fk_client FOREIGN KEY (user_id)
    REFERENCES db_bgefv4_schemav2.client (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidheader
    ADD CONSTRAINT fk_imagemetadata FOREIGN KEY (bidgenre_id)
    REFERENCES db_bgefv4_schemav2.imagemetadata (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.bidheader
    ADD CONSTRAINT fk_soundclipmetadata FOREIGN KEY (bidcontent_id)
    REFERENCES db_bgefv4_schemav2.soundclipmetadata (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.client
    ADD CONSTRAINT fk_bidheader FOREIGN KEY (latestbidheader_id)
    REFERENCES db_bgefv4_schemav2.bidheader (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.client
    ADD CONSTRAINT fk_role FOREIGN KEY (role_id)
    REFERENCES db_bgefv4_schemav2.role (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.gear
    ADD CONSTRAINT fk_bidheader FOREIGN KEY (bidheader_id)
    REFERENCES db_bgefv4_schemav2.bidheader (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.gear
    ADD CONSTRAINT fk_client FOREIGN KEY (user_id)
    REFERENCES db_bgefv4_schemav2.client (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.gear
    ADD CONSTRAINT fk_imagemetadata FOREIGN KEY (gearimage_id)
    REFERENCES db_bgefv4_schemav2.imagemetadata (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS db_bgefv4_schemav2.gear
    ADD CONSTRAINT fk_soundclipmetadata FOREIGN KEY (soundclip_id)
    REFERENCES db_bgefv4_schemav2.soundclipmetadata (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;